runtime: go114
env: standard
instance_class: F4_1G

automatic_scaling:
  target_cpu_utilization: 0.5
  target_throughput_utilization: 0.5
  min_instances: 10
  max_instances: 100
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 10
  
inbound_services:
- warmup

